### ISSUE TITLE
Better handling of run-over.

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/remark-word-wrap#4] opened 2016-01-19 17:59 UTC
![image](https://cloud.githubusercontent.com/assets/1282980/12427231/fff5511a-bed5-11e5-8396-e46ecd1a5e4e.png)

The closing parenthesis here should not be wrapped.

![image](https://cloud.githubusercontent.com/assets/1282980/12427259/252751cc-bed6-11e5-9d87-24f2c053dd98.png)

The trailing space here can be removed.

![image](https://cloud.githubusercontent.com/assets/1282980/12427266/331d45b6-bed6-11e5-96e7-9b8c7c02b317.png)

The commas here should be left on the previous line.

**Comment by wooorm** [comment] 2016-01-20 19:13
How’re you faring with this?

**Comment by ben-eb** [comment] 2016-03-04 01:00
Leaving this here as a reminder: https://github.com/devongovett/linebreak

**Comment by jong** [comment] 2019-01-17 21:07
I am having the same, or a similar problem.

Because of this plugin, when running `remark` on a file multiple times, the output is not always the same.

### My environment

- On Linux 3f006b967a5b 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 Linux
- Using this Dockerfile environment:

```
FROM mhart/alpine-node:10

RUN npm install --global \
    remark-cli@6.0.1 \
    remark-lint@6.0.4 \
    remark-toc@5.1.1 \
    remark-heading-gap@3.1.0 \
    remark-word-wrap@2.0.2
```
Other versions:
```
/tmp # npm --version
6.5.0
/tmp # node --version
v10.15.0
```

### Steps to reproduce

Use this as content for a text file, `test.md`:
```
Excepteur sint occaecat cupidatat non proident, es 
 (<https://example.com/long/path/here/to/disturb/formatting>), Duis aute irure dolor

Single line with [really](example.com/long/link/to/some/amazing/file/on/an/amazing/website.cgi). Foo.
```

Using this as the `remarkrc` contents:
```
{
  "output": true,
  "presets": [],
  "settings": {
    "bullet": "-",
    "fences": true,
    "listItemIndent": "1"
  },
  "plugins": {
    "toc": null,
    "heading-gap": null,
    "word-wrap": {
      "width": 100
    }
  }
}
```

Running using this command:
```
remark --rc-path ./remarkrc test.md -o
```

### Expected behaviour

Running remark to tidy a file should be idempotent - multiple runs on the same file should produce the same file every time.

### Actual behaviour

Spurious whitespace is added when long lines are broken into shorter lines. It seems to be related to any line that is not 'plain text' - it contains "`" or a long link, or something else. Not quite sure.

First run of the sample file:
```
Excepteur sint occaecat cupidatat non proident, es (
<https://example.com/long/path/here/to/disturb/formatting>
), Duis aute irure dolor

Single line with [really](example.com/long/link/to/some/amazing/file/on/an/amazing/website.cgi)
. Foo.
```

Second run of the sample file:
```
Excepteur sint occaecat cupidatat non proident, es ( 
<https://example.com/long/path/here/to/disturb/formatting>
 ), Duis aute irure dolor

Single line with [really](example.com/long/link/to/some/amazing/file/on/an/amazing/website.cgi)
 . Foo.
```

Third run of the sample file:
```
Excepteur sint occaecat cupidatat non proident, es (  
<https://example.com/long/path/here/to/disturb/formatting>
  ), Duis aute irure dolor

Single line with [really](example.com/long/link/to/some/amazing/file/on/an/amazing/website.cgi)
  . Foo.
```

As it is, we can't run this tidy on our docs repo. :(

**Comment by jong** [comment] 2019-01-18 23:11
I opened a PR related to trailing punctuation, but it doesn't completely address the problem in my previous comment - there is still something weird happening that makes the reformat not idempotent. In our docs repo we are seeing weird spacing in this case:

```
some text on this line
    other text on this line
```

Being reformatted as:

```
some text on this line
     other text on this line
```
(there is one additional space inserted in front of the second line). I would expect in my contrived example for things to be either reformatted on to the same line, or leading spaces removed.

I looked for a bit and I couldn't tell what was happening 🤷‍♂️ - seems like maybe a `\n` is being turned into a space or something? The `getWords` function nukes any newlines, but the subsequent `split` turns all spaces into empty words, which I think somehow introduces the extra space when the empty 'words' are re-joined.

**Comment by wooorm** [comment] 2019-06-15 16:46
I’m closing the issues here and archiving the repo. It isn’t really maintained, was never finished (it’s not a task very suitable to syntax trees, but could work in a compiler/generator/stringifier). [Prettier](https://github.com/prettier/prettier) is the better option.

**Closed as completed by wooorm** 2019-06-15 16:46 UTC
Labels: enhancement, help wanted
